set(source_list ${source_list}
${PROJ_PATH}/Core/Src/system_stm32f4xx.c
${PROJ_PATH}/Core/Src/main.c
${PROJ_PATH}/Core/Src/stm32f4xx_it.c
${PROJ_PATH}/Core/startup_stm32f401xe.s
${PROJ_PATH}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_rcc.c
${PROJ_PATH}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal.c
${PROJ_PATH}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_gpio.c
${PROJ_PATH}/Drivers/STM32F4xx_HAL_Driver/Src/Legacy/stm32f4xx_hal_can.c
${PROJ_PATH}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_cortex.c
${PROJ_PATH}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_dma.c
${PROJ_PATH}/Drivers/STM32F4xx_HAL_Driver/Src/stm32f4xx_hal_uart.c
${PROJ_PATH}/Middlewares/BSP/Src/HMC.c
${PROJ_PATH}/Middlewares/BSP/Src/NVIC.c
${PROJ_PATH}/Middlewares/BSP/Src/MPU6050.c
${PROJ_PATH}/Middlewares/BSP/Src/myiic.c
${PROJ_PATH}/Middlewares/BSP/Src/MS5611.c
${PROJ_PATH}/Middlewares/BSP/Src/usart.c
${PROJ_PATH}/Middlewares/BSP/Src/Receiver.c
${PROJ_PATH}/Middlewares/BSP/Src/MotorPWM.c
${PROJ_PATH}/Middlewares/Third_Party/Src/os_cpu_a.S
${PROJ_PATH}/Middlewares/Third_Party/Src/ucos_ii.c
)
